# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Indiv_Score_Test_meta <- function(U, V) {
    .Call(`_MetaSTAAR_Indiv_Score_Test_meta`, U, V)
}

MetaSTAAR_O_SMMAT <- function(x, Cov, weights_B, weights_S, weights_A, mac, mac_thres = 10L) {
    .Call(`_MetaSTAAR_MetaSTAAR_O_SMMAT`, x, Cov, weights_B, weights_S, weights_A, mac, mac_thres)
}

